"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AwsPollyService = exports.AwsS3Service = exports.AwsComprehendService = exports.AwsTextractService = exports.AwsBedrockService = void 0;
var aws_bedrock_service_1 = require("./aws-bedrock.service");
Object.defineProperty(exports, "AwsBedrockService", { enumerable: true, get: function () { return aws_bedrock_service_1.AwsBedrockService; } });
var aws_textract_service_1 = require("./aws-textract.service");
Object.defineProperty(exports, "AwsTextractService", { enumerable: true, get: function () { return aws_textract_service_1.AwsTextractService; } });
var aws_comprehend_service_1 = require("./aws-comprehend.service");
Object.defineProperty(exports, "AwsComprehendService", { enumerable: true, get: function () { return aws_comprehend_service_1.AwsComprehendService; } });
var aws_s3_service_1 = require("./aws-s3.service");
Object.defineProperty(exports, "AwsS3Service", { enumerable: true, get: function () { return aws_s3_service_1.AwsS3Service; } });
var aws_polly_service_1 = require("./aws-polly.service");
Object.defineProperty(exports, "AwsPollyService", { enumerable: true, get: function () { return aws_polly_service_1.AwsPollyService; } });
